### ISSUE TITLE
Tests failing on parseJSON

### ISSUE THREAD

**Issue by x0s** [blenzi/VideoSplitter#3]
Here is my log

```shell
$ python -m unittest discover test
Writing csv file /tmp/tmpgmtmm3ie/test_3_videos.keypoints.csv
Writing csv file /tmp/tmpgmtmm3ie/test_3_videos.rejected.csv
Writing csv file /tmp/tmpgmtmm3ie/test_3_videos.states.csv
Writing frame labels to /tmp/tmpgmtmm3ie/test_3_videos.labels.csv
Extracting 2 frames per state (10 in total) to /tmp/tmpgmtmm3ie
F......Writing csv file /tmp/tmpcdb9cetr/test_3_videos.keypoints.csv
Writing csv file /tmp/tmpcdb9cetr/test_3_videos.rejected.csv
Writing csv file /tmp/tmpcdb9cetr/test_3_videos.states.csv
.
======================================================================
FAIL: test_updateValues_withoutChange (test_checkAnnotations.test_checkAnnotations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/x0s/Projets/DeepLearning/data4good/pyronear/dev/VideoSplitter/test/test_checkAnnotations.py", line 39, in test_updateValues_withoutChange
    pd.testing.assert_frame_equal(labels, self.checker.labels)
  File "/home/x0s/.virtualenvs/pyro36/lib/python3.6/site-packages/pandas/util/testing.py", line 1402, in assert_frame_equal
    obj="{obj}.iloc[:, {idx}]".format(obj=obj, idx=i),
  File "/home/x0s/.virtualenvs/pyro36/lib/python3.6/site-packages/pandas/util/testing.py", line 1207, in assert_series_equal
    obj="{obj}".format(obj=obj),
  File "pandas/_libs/testing.pyx", line 65, in pandas._libs.testing.assert_almost_equal
  File "pandas/_libs/testing.pyx", line 178, in pandas._libs.testing.assert_almost_equal
  File "/home/x0s/.virtualenvs/pyro36/lib/python3.6/site-packages/pandas/util/testing.py", line 932, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 6] are different

DataFrame.iloc[:, 6] values are different (40.0 %)
[left]:  [2, 2, 0, 0, 0, 0, 2, 2, 2, 2]
[right]: [2, 2, 1, 1, 1, 1, 2, 2, 2, 2]

----------------------------------------------------------------------
Ran 8 tests in 1.480s

FAILED (failures=1)
```

**Comment by blenzi** [comment]
Thanks, @x0s . It is a known issue (see https://github.com/blenzi/VideoSplitter/blob/parseJSON/test/test_checkAnnotations.py#L37) but good to have it open.

It occurs because the annotation software uses N/A (value = 0) for the location while it is not really relevant, while the code here sets is to False (value = 1).

I sketched a fix that introduced a table with the description of each field to appear in `checkAnnotations.py` (e.g. 'loc_confidence': 'Location') the values and corresponding words (e.g. 0: N/A, 1: Not precise, 2: Precise) but did not finish it. If you have a suggestion...
